name: Pandoc Create ODT

on: push

jobs:
  pandoc_build_output:
    if: ${{ !contains(github.event.head_commit.message, '#GHActions') }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker://pandoc/core:3.1.13
        with:
          args: >-
            --standalone
            --from=markdown
            --to=docx
            --metadata-file ./.pandoc/core.yml
            --lua-filter ./.pandoc/pagebreak.lua
            --output=CV.docx
            ./.src/CV.source.md
      - uses: docker://pandoc/core:3.1.13
        with:
          args: >-
            --standalone
            --from=markdown
            --to=markdown
            --metadata-file ./.pandoc/core.yml
            --lua-filter ./.pandoc/pagebreak.lua
            --output=CV.md
            ./.src/CV.source.md
      - uses: docker://pandoc/core:3.1.13
        with:
          args: >-
            --standalone
            --from=markdown
            --to=rtf
            --metadata-file ./.pandoc/core.yml
            --lua-filter ./.pandoc/pagebreak.lua
            --output=CV.rtf
            ./.src/CV.source.md

      - run: sudo apt-get -y update && sudo apt-get -y install pandoc pdflatex texlive-latex-recommended letltxmacro texlive-latex-extra texlive-fonts-extra
      - run: pandoc --standalone --metadata-file ./.pandoc/core.yml --metadata-file ./.pandoc/latex.yml --from=markdown --to=pdf -t latex --output=CV.alt.pdf ./.src/CV.source.md
      # - uses: docker://pandoc/latex:3.1.13-ubuntu
      #   with:
      #     args: >-
      #       --standalone
      #       --metadata-file ./.pandoc/core.yml ./.pandoc/latex.yml
      #       --from=markdown
      #       --to=pdf
      #       --output=CV.pdf
      #       ./.src/CV.source.md

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(ODT): #GHActions - generate ODT File"
          commit_user_name: Repo Actions bot
          commit_user_email: actions@shadowguardian507-irl.co.uk
          commit_author: Repo Actions bot <actions@shadowguardian507-irl.co.uk>
          
