name: Pandoc Create ODT

on: push

jobs:
  convert_via_pandoc:
    if: ${{ !contains(github.event.head_commit.message, '#GHActions') }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: ls -alh ./
      - run: rm -f ./CV.odt
      - run: rm -f ./CV.alt.pdf
      - run: rm -f ./CV.rtf
      - uses: docker://pandoc/core:3.1.13
        with:
          args: >-
            --standalone
            --from=markdown
            --to=odt
            --output=CV.odt
            ./CV.md
      - uses: docker://pandoc/core:3.1.13
        with:
          args: >-
            --standalone
            --from=markdown
            --to=rtf
            --output=CV.rtf
            ./CV.md
      - uses: docker://pandoc/latex:3.1.13
        with:
          args: >-
            --standalone
            --from=markdown
            --to=pdf
            --output=CV.alt.pdf
            ./CV.md

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(ODT): #GHActions - generate ODT File"
          commit_user_name: Repo Actions bot
          commit_user_email: actions@shadowguardian507-irl.co.uk
          commit_author: Repo Actions bot <actions@shadowguardian507-irl.co.uk>
          
